kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "csi-disk-plugin.extensionsGroup" . }}:kube-system:csi-controller-ali-plugin
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "watch", "create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "csi-disk-plugin.extensionsGroup" . }}:csi-controller-ali-plugin
subjects:
{{- if .Values.global.useTokenRequestor }}
- kind: ServiceAccount
  name: csi-controller-ali-plugin
  namespace: kube-system
{{- else }}
- kind: User
  name: system:csi-controller-ali-plugin
{{- end }}
roleRef:
  kind: ClusterRole
  name: {{ include "csi-disk-plugin.extensionsGroup" . }}:kube-system:csi-controller-ali-plugin
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kube-system
  name: csi-controller-ali-plugin
rules:
- apiGroups: [""]
  resources: ["configmaps", "nodes"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-controller-ali-plugin
  namespace: kube-system
subjects:
{{- if .Values.global.useTokenRequestor }}
- kind: ServiceAccount
  name: csi-controller-ali-plugin
  namespace: kube-system
{{- else }}
- kind: User
  name: system:csi-controller-ali-plugin
{{- end }}
roleRef:
  kind: Role
  name: csi-controller-ali-plugin
  apiGroup: rbac.authorization.k8s.io
